apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: strapi-secrets
  namespace: cms-strapi

spec:
  refreshInterval: "15m"

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: strapi-secrets
    creationPolicy: Owner

  data:

    # Server
    - secretKey: HOST
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: HOST

    - secretKey: PORT
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: PORT

    - secretKey: PUBLIC_URL
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: PUBLIC_URL

    # Admin Panel
    - secretKey: ADMIN_URL
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: ADMIN_URL

    # Strapi Core Secrets
    - secretKey: APP_KEYS
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: APP_KEYS

    - secretKey: API_TOKEN_SALT
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: API_TOKEN_SALT

    - secretKey: ADMIN_JWT_SECRET
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: ADMIN_JWT_SECRET

    - secretKey: JWT_SECRET
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: JWT_SECRET

    - secretKey: TRANSFER_TOKEN_SALT
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: TRANSFER_TOKEN_SALT

    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: ENCRYPTION_KEY

    # Database
    - secretKey: DATABASE_CLIENT
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: DATABASE_CLIENT

    - secretKey: DATABASE_HOST
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: DATABASE_HOST

    - secretKey: DATABASE_PORT
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: DATABASE_PORT

    - secretKey: DATABASE_NAME
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: DATABASE_NAME

    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: DATABASE_USERNAME

    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: DATABASE_PASSWORD

    - secretKey: DATABASE_SSL
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: DATABASE_SSL

    # Email
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: RESEND_API_KEY

    - secretKey: SMTP_FROM
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: SMTP_FROM

    # Cloudinary
    - secretKey: CLOUDINARY_NAME
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: CLOUDINARY_NAME

    - secretKey: CLOUDINARY_KEY
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: CLOUDINARY_KEY

    - secretKey: CLOUDINARY_SECRET
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: CLOUDINARY_SECRET

    # Hetzner Object Storage / S3
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: S3_ENDPOINT

    - secretKey: S3_REGION
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: S3_REGION

    - secretKey: S3_BUCKET
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: S3_BUCKET

    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: S3_ACCESS_KEY_ID

    - secretKey: S3_ACCESS_SECRET
      remoteRef:
        key: six-degrees/clients/cms/secrets
        property: S3_ACCESS_SECRET