apiVersion: v1
kind: Service
metadata:
  name: cms-strapi-svc
  namespace: cms-strapi
spec:
  selector:
    app: cms-strapi

  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337

  type: ClusterIP